stages:
  - DEVDEPLOY-DEPLOY
  - PRODUCTION-DEPLOY 
  
dev-deployment:
  stage: DEVDEPLOY-DEPLOY
  tags:
       -  predevwebserver
  only:
    refs:
       - development
  script:
       - sudo docker exec -i devlaravel bash -c 'cd /var/www/html/; rm .env; git pull; cp deployments/.env.development .env'

prod-deployment:
  stage: PRODUCTION-DEPLOY
  tags:
       - predevwebserver
  only:
    refs:
       - master
  script:
       - sudo docker exec -i gofer bash -c 'cd /var/www/html/; rm .env; git pull; cp deployments/.env.example .env'